parameters:
    coreshop.dto.add_to_cart.class: 'CoreShop\Bundle\OrderBundle\DTO\AddToCart'

imports:
    - { resource: "services/order.yml" }
    - { resource: "services/order_invoice.yml" }
    - { resource: "services/order_shipment.yml" }
    - { resource: "services/cart-price-rules.yml" }
    - { resource: "services/workflow.yml" }
    - { resource: "services/pdf.yml" }
    - { resource: "services/purchasable.yml" }
    - { resource: "services/context.yml" }
    - { resource: "services/commands.yml" }
    - { resource: "services/profiler.yml" }
    - { resource: "services/cart.yml" }
    - { resource: "services/grid_config.yml" }
    - { resource: "services/payment.yml" }
    - { resource: "services/forms.yml" }
    - { resource: "services/checkout_listener.yml" }

services:
    _defaults:
        public: true

    coreshop.order.configurator.session_cart: '@CoreShop\Bundle\OrderBundle\Session\SessionCartConfigurator'
    CoreShop\Bundle\OrderBundle\Session\SessionCartConfigurator:
        tags:
            - { name: pimcore.session.configurator }

    coreshop.cart.manager: '@CoreShop\Bundle\OrderBundle\Manager\CartManager'
    CoreShop\Component\Order\Manager\CartManagerInterface: '@CoreShop\Bundle\OrderBundle\Manager\CartManager'
    CoreShop\Bundle\OrderBundle\Manager\CartManager:
        arguments:
            - '@coreshop.cart_processor'
            - '@coreshop.object_service'
            - '%coreshop.folder.cart%'

    coreshop.cart_item.quantity_modifier: '@CoreShop\Component\StorageList\StorageListItemQuantityModifier'
    CoreShop\Component\StorageList\StorageListItemQuantityModifier: ~

    coreshop.cart.modifier: '@CoreShop\Component\Order\Cart\CartModifier'
    CoreShop\Component\Order\Cart\CartModifier:
        arguments:
            - '@coreshop.cart_item.quantity_modifier'
            - '@event_dispatcher'

    coreshop.order.invoice.processable:
        class: CoreShop\Component\Order\Processable\ProcessableOrderItems
        arguments:
            - '@coreshop.repository.order_invoice'
            - !php/const CoreShop\Component\Order\InvoiceStates::STATE_CANCELLED

    coreshop.order.shipment.processable:
        class: CoreShop\Component\Order\Processable\ProcessableOrderItems
        arguments:
            - '@coreshop.repository.order_shipment'
            - !php/const CoreShop\Component\Order\ShipmentStates::STATE_CANCELLED

    coreshop.transformer.event_dispatcher: '@CoreShop\Component\Order\Transformer\TransformerEventDispatcher'
    CoreShop\Component\Order\Transformer\TransformerEventDispatcher:
        public: false
        arguments:
            - '@event_dispatcher'

    coreshop.cart_processor.composite: '@CoreShop\Component\Order\Processor\CompositeCartProcessor'
    CoreShop\Component\Order\Processor\CartProcessorInterface: '@CoreShop\Component\Order\Processor\CompositeCartProcessor'
    CoreShop\Component\Order\Processor\CompositeCartProcessor: ~

    coreshop.cart.expire: '@CoreShop\Bundle\OrderBundle\Expiration\CartExpiration'
    CoreShop\Bundle\OrderBundle\Expiration\CartExpiration:
        shared: false
        arguments:
             - '@coreshop.repository.cart'

    coreshop.order.expire: '@CoreShop\Bundle\OrderBundle\Expiration\OrderExpiration'
    CoreShop\Bundle\OrderBundle\Expiration\OrderExpiration:
        shared: false
        arguments:
             - '@coreshop.repository.order'
             - '@coreshop.state_machine_applier'

    coreshop.proportional_integer_distributor: '@CoreShop\Component\Order\Distributor\ProportionalIntegerDistributor'
    CoreShop\Component\Order\Distributor\ProportionalIntegerDistributorInterface: '@CoreShop\Component\Order\Distributor\ProportionalIntegerDistributor'
    CoreShop\Component\Order\Distributor\ProportionalIntegerDistributor: ~

    coreshop.custom_factory.adjustment: '@CoreShop\Component\Order\Factory\AdjustmentFactory'
    CoreShop\Component\Order\Factory\AdjustmentFactoryInterface: '@CoreShop\Component\Order\Factory\AdjustmentFactory'
    CoreShop\Component\Order\Factory\AdjustmentFactory:
        decorates: coreshop.factory.adjustment
        decoration_priority: 256
        public: false
        arguments:
            - '@CoreShop\Component\Order\Factory\AdjustmentFactory.inner'

    coreshop.custom_factory.cart_item: '@CoreShop\Component\Order\Factory\CartItemFactory'
    CoreShop\Component\Order\Factory\CartItemFactory:
        decorates: coreshop.factory.cart_item
        decoration_priority: 256
        public: false
        arguments:
            - '@CoreShop\Component\Order\Factory\CartItemFactory.inner'

    coreshop.factory.add_to_cart: '@CoreShop\Bundle\OrderBundle\Factory\AddToCartFactory'
    CoreShop\Bundle\OrderBundle\Factory\AddToCartFactory:
        arguments:
            - '%coreshop.dto.add_to_cart.class%'
