parameters:
    coreshop.session.cart: 'coreshop.cart'
    coreshop.form.type.cart.validation_groups: [coreshop]
    coreshop.form.type.cart_item.validation_groups: [coreshop]

services:
    _defaults:
        public: true

    CoreShop\Bundle\OrderBundle\Form\Type\CartType:
        arguments:
            - '%coreshop.model.cart.class%'
            - '%coreshop.form.type.cart.validation_groups%'
        tags:
            - { name: form.type }

    CoreShop\Bundle\OrderBundle\Form\Type\CartCreationType:
        arguments:
            - '%coreshop.model.cart.class%'
            - '%coreshop.form.type.cart.validation_groups%'
        tags:
            - { name: form.type }

    coreshop.form.data_mapper.cart_item_quantity.property_mapper:
        class: Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper
        arguments:
            - '@property_accessor'

    coreshop.form.data_mapper.cart_item_quantity: '@CoreShop\Bundle\OrderBundle\Form\DataMapper\CartItemQuantityDataMapper'
    CoreShop\Bundle\OrderBundle\Form\DataMapper\CartItemQuantityDataMapper:
        arguments:
            - '@coreshop.cart_item.quantity_modifier'
            - '@coreshop.form.data_mapper.cart_item_quantity.property_mapper'

    CoreShop\Bundle\OrderBundle\Form\Type\CartItemType:
        arguments:
            - '%coreshop.model.cart_item.class%'
            - '%coreshop.form.type.cart_item.validation_groups%'
            - '@coreshop.form.data_mapper.cart_item_quantity'
        tags:
            - { name: form.type }

    CoreShop\Bundle\OrderBundle\Form\Type\CartCreationCartItemType:
        arguments:
            - '%coreshop.model.cart_item.class%'
            - '%coreshop.form.type.cart_item.validation_groups%'
            - '@coreshop.form.data_mapper.cart_item_quantity'
        tags:
            - { name: form.type }
