services:
    CoreShop\Bundle\OrderBundle\EventListener\CheckoutCartLocaleAssignerListener:
        arguments:
            - '@coreshop.context.locale'
        tags:
            - { name: kernel.event_listener, event: coreshop.checkout.do.pre, method: assignLocaleOnCheckout }
