services:
    _defaults:
        public: true

    coreshop.command.cart.expire:
        class: CoreShop\Bundle\OrderBundle\Command\CartExpireCommand
        arguments:
            - '@coreshop.cart.expire'
            - '%coreshop.cart.expiration.days%'
            - { anonymous: '%coreshop.cart.expiration.anonymous%', customer: '%coreshop.cart.expiration.customer%'}
        tags:
          - { name: console.command, command: 'coreshop:cart:expire' }

    coreshop.command.order.expire:
        class: CoreShop\Bundle\OrderBundle\Command\OrderExpireCommand
        arguments:
            - '@coreshop.order.expire'
            - '%coreshop.order.expiration.days%'
        tags:
          - { name: console.command, command: 'coreshop:order:expire' }