services:
    CoreShop\Bundle\OrderBundle\Controller\OrderController:
        abstract: true
        calls:
            - ['setEventDispatcher', ['@event_dispatcher']]
            - ['setObjectNoteService', ['@CoreShop\Component\Pimcore\DataObject\NoteServiceInterface']]
            - ['setAddressFormatter', ['@CoreShop\Component\Address\Formatter\AddressFormatterInterface']]
            - ['setJmsSerializer', ['@jms_serializer.serializer']]
            - ['setWorkflowStateManager', ['@CoreShop\Bundle\WorkflowBundle\StateManager\WorkflowStateInfoManagerInterface']]
            - ['setInvoiceProcessableHelper', ['@coreshop.order.invoice.processable']]
            - ['setShipmentProcessableHelper', ['@coreshop.order.shipment.processable']]
            - ['setOrderInvoiceRepository', ['@coreshop.repository.order_invoice']]
            - ['setOrderShipmentRepository', ['@coreshop.repository.order_shipment']]
            - ['setPaymentRepository', ['@coreshop.repository.payment']]
            - ['setOrderEditPossible', ['@CoreShop\Component\Order\OrderEditPossibleInterface']]

    CoreShop\Bundle\OrderBundle\Controller\OrderCreationController:
        abstract: true
        calls:
            - ['setAddressFormatter', ['@CoreShop\Component\Address\Formatter\AddressFormatterInterface']]

    CoreShop\Bundle\OrderBundle\Controller\OrderDocumentPrintController:
        autowire: true
        autoconfigure: true
        public: true
        tags: [ 'controller.service_arguments' ]

