services:
    _defaults:
        public: true

    CoreShop\Component\Order\Context\FixedCartContext:
        tags:
            - { name: coreshop.context.cart, priority: -100 }


    CoreShop\Component\Order\Context\CartContext:
        decorates: 'coreshop.storage_list.context.factory.order'
        arguments:
            - '@coreshop.factory.order'

    CoreShop\Component\Order\Cart\CartContextResolverInterface: '@CoreShop\Component\Order\Cart\CartContextResolver'
    CoreShop\Component\Order\Cart\CartContextResolver: ~
