services:
    coreshop.datahub.graphql.querytypegenerator.resource.cart_price_rule:
        class: CoreShop\Component\Resource\DataHub\QueryType\Resource
        arguments:
            - '@Pimcore\Bundle\DataHubBundle\GraphQL\Service'
            - '@coreshop.data_hub.doctrine_provider'
            - '%coreshop.model.cart_price_rule.class%'
        tags:
            - { name: pimcore.datahub.graphql.querytypegenerator, id: typegenerator_querydatatype_coreShopCartPriceRule }
