parameters:
    coreshop.form.type.add_to_cart.validation_groups: [coreshop]

services:
    CoreShop\Bundle\OrderBundle\Form\Type\AddToCartType:
        arguments:
            - '%coreshop.dto.add_to_cart.class%'
            - '%coreshop.form.type.add_to_cart.validation_groups%'
        tags:
            - { name: form.type }
