parameters:
    coreshop.form.type.add_to_cart.validation_groups: [coreshop]

services:
    coreshop.form.type.add_to_cart:
        class: CoreShop\Bundle\OrderBundle\Form\Type\AddToCartType
        arguments:
            - 'CoreShop\Bundle\OrderBundle\DTO\AddToCart'
            - '%coreshop.form.type.add_to_cart.validation_groups%'
        tags:
            - { name: form.type }
