services:
    _defaults:
        public: true

    CoreShop\Bundle\OrderBundle\Pimcore\GridColumnConfig\Operator\Factory\OrderStateFactory:
        arguments:
            - '@coreshop.workflow.state_info_manager'
        tags:
            - { name: pimcore.data_object.grid_column_config.operator_factory, id: coreshop_order_state }

    CoreShop\Bundle\OrderBundle\Pimcore\GridColumnConfig\Operator\Factory\PriceFormatterFactory:
        arguments:
            - '@coreshop.money_formatter'
            - '@coreshop.context.locale'
        tags:
            - { name: pimcore.data_object.grid_column_config.operator_factory, id: coreshop_price_formatter }
