services:
    _defaults:
        public: true

    coreshop.data_object.grid_column_config.operator.factory.order_state:
        class: CoreShop\Bundle\OrderBundle\Pimcore\GridColumnConfig\Operator\Factory\OrderStateFactory
        arguments:
            - '@coreshop.workflow.state_manager'
        tags:
            - { name: pimcore.data_object.grid_column_config.operator_factory, id: OrderState }

    coreshop.data_object.grid_column_config.operator.factory.price_formatter:
        class: CoreShop\Bundle\OrderBundle\Pimcore\GridColumnConfig\Operator\Factory\PriceFormatterFactory
        arguments:
            - '@coreshop.money_formatter'
            - '@coreshop.context.locale'
        tags:
            - { name: pimcore.data_object.grid_column_config.operator_factory, id: PriceFormatter }
