services:
    _defaults:
        public: true

    coreshop.order_invoice.number_generator.default:
        class: CoreShop\Component\Order\NumberGenerator\SequenceNumberGenerator
        arguments:
            - '@CoreShop\Component\Sequence\Generator\SequenceGeneratorInterface'
            - 'invoice'

    CoreShop\Component\Order\Transformer\OrderItemToInvoiceItemTransformer:
        arguments:
            - '@CoreShop\Component\Resource\Service\FolderCreationServiceInterface'
            - '@CoreShop\Component\Order\Transformer\TransformerEventDispatcherInterface'

    CoreShop\Component\Order\Transformer\OrderToInvoiceTransformer:
        arguments:
            - '@CoreShop\Component\Order\Transformer\OrderItemToInvoiceItemTransformer'
            - '@coreshop.order_invoice.number_generator.default'
            - '@CoreShop\Component\Resource\Service\FolderCreationServiceInterface'
            - '@coreshop.repository.order_item'
            - '@coreshop.factory.order_invoice_item'
            - '@coreshop.repository.order_invoice'
            - '@CoreShop\Component\Order\Transformer\TransformerEventDispatcherInterface'
            - '@coreshop.factory.adjustment'

    coreshop.order.transformer.order_to_invoice.state_applier:
        class: CoreShop\Component\Order\Transformer\OrderToOrderDocumentTransformerWorkflowApplier
        decorates: CoreShop\Component\Order\Transformer\OrderToInvoiceTransformer
        arguments:
             - '@coreshop.order.transformer.order_to_invoice.state_applier.inner'
             - '@CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManagerInterface'
             - !php/const CoreShop\Component\Order\InvoiceStates::STATE_NEW
             - !php/const CoreShop\Component\Order\InvoiceTransitions::IDENTIFIER
             - !php/const CoreShop\Component\Order\InvoiceTransitions::TRANSITION_CREATE
