services:
  coreshop.order.number_generator.default:
    class: CoreShop\Bundle\CoreBundle\NumberGenerator\OrderNumberGenerator
    arguments: ['@coreshop.sequence.generator', 'order', '@coreshop.configuration.service']

  coreshop.quote.number_generator.default:
    class: CoreShop\Bundle\CoreBundle\NumberGenerator\QuoteNumberGenerator
    arguments: ['@coreshop.sequence.generator', 'quote', '@coreshop.configuration.service']

  coreshop.order.transformer.cart_item_to_order_item:
    class: CoreShop\Bundle\OrderBundle\Transformer\CartItemToOrderItemTransformer
    arguments:
      - '@coreshop.object_service'
      - '%coreshop.folder.order_item%'
      - '@coreshop.transformer.event_dispatcher'
      - '@coreshop.currency_converter'

  coreshop.order.transformer.cart_to_order:
    class: CoreShop\Bundle\OrderBundle\Transformer\CartToOrderTransformer
    arguments:
      - '@coreshop.order.transformer.cart_item_to_order_item'
      - '@coreshop.core.key_transformer'
      - '@coreshop.order.number_generator.default'
      - '%coreshop.folder.order%'
      - '@coreshop.object_service'
      - '@coreshop.context.locale'
      - '@coreshop.factory.order_item'
      - '@coreshop.context.store'
      - '@coreshop.cart_price_rule.order.processor'
      - '@coreshop.transformer.event_dispatcher'
      - '@coreshop.currency_converter'
      - '@coreshop.resource.object_cloner'

  coreshop.order.transformer.cart_item_to_quote_item:
    class: CoreShop\Bundle\OrderBundle\Transformer\CartItemToQuoteItemTransformer
    arguments:
      - '@coreshop.object_service'
      - '%coreshop.folder.quote_item%'
      - '@coreshop.transformer.event_dispatcher'
      - '@coreshop.currency_converter'

  coreshop.order.transformer.cart_to_quote:
    class: CoreShop\Bundle\OrderBundle\Transformer\CartToQuoteTransformer
    arguments:
      - '@coreshop.order.transformer.cart_item_to_quote_item'
      - '@coreshop.core.key_transformer'
      - '@coreshop.quote.number_generator.default'
      - '%coreshop.folder.quote%'
      - '@coreshop.object_service'
      - '@coreshop.context.locale'
      - '@coreshop.factory.quote_item'
      - '@coreshop.context.store'
      - '@coreshop.cart_price_rule.order.processor'
      - '@coreshop.transformer.event_dispatcher'
      - '@coreshop.currency_converter'
      - '@coreshop.resource.object_cloner'

  coreshop.factory.cart:
    class: CoreShop\Component\Order\Factory\CartFactory
    arguments:
      - '%coreshop.model.cart.class%'
      - '@coreshop.context.currency'
      - '@coreshop.context.store'

  coreshop.mail.processor.order:
    class: CoreShop\Component\Core\Order\OrderMailProcessor
    arguments:
     - '@coreshop.money_formatter'
     - '@coreshop.repository.order_invoice'
     - '@coreshop.repository.order_shipment'
     - '@coreshop.renderer.order.pdf'

  coreshop.renderer.order.pdf:
    class: CoreShop\Bundle\CoreBundle\Order\Renderer\OrderDocumentPdfRenderer
    arguments:
      - '@fragment.renderer.inline'
      - '@coreshop.configuration.service'
      - '@coreshop.renderer.pdf'

  coreshop.renderer.order.pdf.asset:
    class: CoreShop\Bundle\CoreBundle\Order\Renderer\AssetOrderDocumentPdfRenderer
    decorates: coreshop.renderer.order.pdf
    arguments: ['@coreshop.renderer.order.pdf.asset.inner']
