services:
    _defaults:
        public: true

    coreshop.order.number_generator.default:
        class: CoreShop\Component\Order\NumberGenerator\SequenceNumberGenerator
        arguments:
            - '@coreshop.sequence.generator'
            - 'order'

    coreshop.quote.number_generator.default:
        class: CoreShop\Component\Order\NumberGenerator\SequenceNumberGenerator
        arguments:
            - '@coreshop.sequence.generator'
            - 'quote'

    coreshop.order.transformer.cart_item_to_order_item: '@CoreShop\Component\Order\Transformer\CartItemToOrderItemTransformer'
    CoreShop\Component\Order\Transformer\CartItemToOrderItemTransformer:
        arguments:
            - '@coreshop.object_service'
            - '%coreshop.folder.order_item%'
            - '@coreshop.transformer.event_dispatcher'
            - '@coreshop.currency_converter'
            - '@coreshop.translation_locale_provider'

    coreshop.order.transformer.cart_to_order: '@CoreShop\Component\Order\Transformer\CartToOrderTransformer'
    CoreShop\Component\Order\Transformer\CartToOrderTransformer:
        arguments:
            - '@coreshop.order.transformer.cart_item_to_order_item'
            - '@coreshop.core.key_transformer'
            - '@coreshop.order.number_generator.default'
            - '%coreshop.folder.order%'
            - '@coreshop.object_service'
            - '@coreshop.factory.order_item'
            - '@coreshop.transformer.event_dispatcher'
            - '@coreshop.currency_converter'
            - '@coreshop.object_cloner'
            - '@coreshop.repository.cart_price_rule_voucher_code'

    coreshop.order.transformer.cart_to_order.workflow_applier: '@CoreShop\Component\Order\Transformer\CartToOrderTransformerWorkflowApplier'
    CoreShop\Component\Order\Transformer\CartToOrderTransformerWorkflowApplier:
        decorates: 'CoreShop\Component\Order\Transformer\CartToOrderTransformer'
        arguments:
            - '@CoreShop\Component\Order\Transformer\CartToOrderTransformerWorkflowApplier.inner'
            - '@coreshop.state_machine_applier'

    coreshop.order.transformer.cart_item_to_quote_item: '@CoreShop\Component\Order\Transformer\CartItemToQuoteItemTransformer'
    CoreShop\Component\Order\Transformer\CartItemToQuoteItemTransformer:
        arguments:
            - '@coreshop.object_service'
            - '%coreshop.folder.quote_item%'
            - '@coreshop.transformer.event_dispatcher'
            - '@coreshop.currency_converter'
            - '@coreshop.translation_locale_provider'

    coreshop.order.transformer.cart_to_quote: '@CoreShop\Component\Order\Transformer\CartToQuoteTransformer'
    CoreShop\Component\Order\Transformer\CartToQuoteTransformer:
        arguments:
            - '@coreshop.order.transformer.cart_item_to_quote_item'
            - '@coreshop.core.key_transformer'
            - '@coreshop.quote.number_generator.default'
            - '%coreshop.folder.quote%'
            - '@coreshop.object_service'
            - '@coreshop.factory.quote_item'
            - '@coreshop.transformer.event_dispatcher'
            - '@coreshop.currency_converter'
            - '@coreshop.object_cloner'
            - '@coreshop.repository.cart_price_rule_voucher_code'

    CoreShop\Bundle\OrderBundle\Templating\Helper\OrderStateHelperInterface: '@CoreShop\Bundle\OrderBundle\Templating\Helper\OrderStateHelper'
    CoreShop\Bundle\OrderBundle\Templating\Helper\OrderStateHelper:
        arguments:
            - '@coreshop.workflow.state_info_manager'
        tags:
            - { name: templating.helper, alias: coreshop_order_state }

    CoreShop\Bundle\OrderBundle\Twig\OrderStateExtension:
        arguments:
            - '@CoreShop\Bundle\OrderBundle\Templating\Helper\OrderStateHelper'
        tags:
            - { name: twig.extension }
