services:
    _defaults:
        public: true

    coreshop.order.payment_provider: '@CoreShop\Component\Order\Payment\OrderPaymentProvider'
    CoreShop\Component\Order\Payment\OrderPaymentProviderInterface: '@CoreShop\Component\Order\Payment\OrderPaymentProvider'
    CoreShop\Component\Order\Payment\OrderPaymentProvider:
        arguments:
            - '@coreshop.factory.payment'
            - '%coreshop.currency.decimal_factor%'
            - '%coreshop.currency.decimal_precision%'
