services:
    _defaults:
        public: true

    coreshop.order.renderer.pdf: '@CoreShop\Bundle\OrderBundle\Renderer\Pdf\WkHtmlToPdf'
    CoreShop\Bundle\OrderBundle\Renderer\Pdf\PdfRendererInterface: '@CoreShop\Bundle\OrderBundle\Renderer\Pdf\WkHtmlToPdf'
    CoreShop\Bundle\OrderBundle\Renderer\Pdf\WkHtmlToPdf:
        arguments:
            - '%kernel.cache_dir%'
            - '%kernel.project_dir%'

    coreshop.renderer.order.pdf: '@CoreShop\Bundle\OrderBundle\Renderer\OrderDocumentPdfRenderer'
    CoreShop\Bundle\OrderBundle\Renderer\OrderDocumentPdfRenderer:
        arguments:
            - '@fragment.renderer.inline'
            - '@event_dispatcher'
            - '@CoreShop\Bundle\OrderBundle\Renderer\Pdf\PdfRendererInterface'
            - '@coreshop.theme.helper'

    coreshop.renderer.order.pdf.asset: '@CoreShop\Bundle\OrderBundle\Renderer\AssetOrderDocumentPdfRenderer'
    CoreShop\Bundle\OrderBundle\Renderer\AssetOrderDocumentPdfRenderer:
        decorates: coreshop.renderer.order.pdf
        arguments:
            - '@CoreShop\Bundle\OrderBundle\Renderer\AssetOrderDocumentPdfRenderer.inner'
            - '%kernel.environment%'
