services:
    _defaults:
        public: true

    coreshop.cart_collector:
        class: CoreShop\Bundle\OrderBundle\Collector\CartCollector
        arguments:
            - '@coreshop.context.cart'
            - '@coreshop.context.locale'
            - '@Pimcore\Http\Request\Resolver\PimcoreContextResolver'
        tags:
            - { name: data_collector, template: 'CoreShopOrderBundle:Collector:cart.html.twig', id: coreshop.cart_collector }