services:
  coreshop.cart_collector:
    class: CoreShop\Bundle\OrderBundle\Collector\CartCollector
    arguments:
      - '@coreshop.context.cart'
      - '@coreshop.context.locale'
    tags:
      - { name: data_collector, template: 'CoreShopOrderBundle:Collector:cart.html.twig', id: coreshop.cart_collector }