services:
    coreshop.state_machine.marking_store.single_state.order_state:
        class: Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore
        arguments:
            - orderState

    coreshop.state_machine.marking_store.order_pimcore_marketing_store:
        class: CoreShop\Component\Resource\Workflow\MarketingStore\PimcorePersistentMarkingStore
        arguments:
          - '@coreshop.state_machine.marking_store.single_state.order_state'
