parameters:
  coreshop.workflow.manager.order.state_identifier: 'Order State Change'

services:
    coreshop.state_machine_resolver.order:
        public: true
        class: CoreShop\Bundle\OrderBundle\StateResolver\OrderStateResolver
        arguments:
          - '@coreshop.state_machine_manager'

    coreshop.state_machine_resolver.order_payment:
        public: true
        class: CoreShop\Bundle\OrderBundle\StateResolver\OrderPaymentStateResolver
        arguments:
            - '@coreshop.state_machine_manager'

    #coreshop.state_machine_resolver.order_invoice:
    #    public: true
    #    class: CoreShop\Bundle\OrderBundle\StateResolver\OrderDocumentStateResolver
    #   arguments:
    #     - '@coreshop.state_machine_manager'
    #     - '@coreshop.order.invoice.processable'
    #     - !php/const CoreShop\Component\Order\OrderInvoiceTransitions::IDENTIFIER
    #     - !php/const CoreShop\Component\Order\OrderInvoiceTransitions::TRANSITION_READY
    #     - !php/const CoreShop\Component\Order\OrderInvoiceTransitions::TRANSITION_PARTIALLY_INVOICED
    #     - !php/const CoreShop\Component\Order\OrderInvoiceTransitions::TRANSITION_CANCEL
    #     - !php/const CoreShop\Component\Order\OrderInvoiceTransitions::TRANSITION_INVOICED

    coreshop.state_machine_resolver.order_shipment:
        public: true
        class: CoreShop\Bundle\OrderBundle\StateResolver\OrderShippingStateResolver
        arguments:
          - '@coreshop.state_machine_manager'
          - '@coreshop.repository.order_shipment'

    coreshop.state_machine.marking_store.single_state.order_payment_state:
        class: Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore
        arguments:
            - paymentState

    coreshop.state_machine.marking_store.order_payment_pimcore_marking_store:
        class: CoreShop\Component\Resource\Workflow\MarkingStore\PimcorePersistentMarkingStore
        arguments:
            - '@coreshop.state_machine.marking_store.single_state.order_payment_state'

    coreshop.state_machine.marking_store.single_state.order_state:
        class: Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore
        arguments:
            - orderState

    coreshop.state_machine.marking_store.order_pimcore_marking_store:
        class: CoreShop\Component\Resource\Workflow\MarkingStore\PimcorePersistentMarkingStore
        arguments:
          - '@coreshop.state_machine.marking_store.single_state.order_state'

    coreshop.state_machine.marking_store.single_state.order_shipment_state:
        class: Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore
        arguments:
            - shippingState

    coreshop.state_machine.marking_store.order_shipment_pimcore_marking_store:
        class: CoreShop\Component\Resource\Workflow\MarkingStore\PimcorePersistentMarkingStore
        arguments:
          - '@coreshop.state_machine.marking_store.single_state.order_shipment_state'

    coreshop.state_machine.marking_store.single_state.order_invoice_state:
        class: Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore
        arguments:
            - invoiceState

    coreshop.state_machine.marking_store.order_invoice_pimcore_marking_store:
        class: CoreShop\Component\Resource\Workflow\MarkingStore\PimcorePersistentMarkingStore
        arguments:
          - '@coreshop.state_machine.marking_store.single_state.order_invoice_state'

    coreshop.state_machine.marking_store.single_state.shipment_state:
        class: Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore
        arguments:
            - state

    coreshop.state_machine.marking_store.shipment_pimcore_marking_store:
        class: CoreShop\Component\Resource\Workflow\MarkingStore\PimcorePersistentMarkingStore
        arguments:
          - '@coreshop.state_machine.marking_store.single_state.shipment_state'

    coreshop.workflow.state_manager:
        class: CoreShop\Bundle\OrderBundle\Workflow\WorkflowStateManager
        arguments:
          - '@coreshop.state_machine_manager'
          - '@pimcore.translator'
          - '%coreshop.workflow.manager.order.state_identifier%'
          - '%coreshop.state_machine.colors%'
        tags:
          - {name: coreshop.workflow.manager, type: '%coreshop.model.order.class%' }

    coreshop.workflow.state_history_logger:
        class: CoreShop\Bundle\OrderBundle\Workflow\OrderStateHistoryLogger
        arguments:
          - '@coreshop.repository.order'
          - '@coreshop.state_machine_manager'
          - '@coreshop.object_note_service'
          - '@pimcore.translator'
          - '%coreshop.workflow.manager.order.state_identifier%'
        tags:
          - {name: coreshop.workflow.manager, type: '%coreshop.model.order.class%' }


    #coreshop.workflow.order_document.invoice.creation_listener:
    #    class: CoreShop\Bundle\OrderBundle\EventListener\OrderDocumentCreationListener
    #    arguments:
    #        - '@coreshop.state_machine_resolver.order_invoice'
    #    tags:
    #        - { name: kernel.event_listener, event: coreshop.invoice.post_transform, method: onOrderDocumentCreated }

    #coreshop.workflow.order_document.shipment.creation_listener:
    #    class: CoreShop\Bundle\OrderBundle\EventListener\OrderDocumentCreationListener
    #    arguments:
    #        - '@coreshop.state_machine_resolver.order_shipment'
    #    tags:
    #        - { name: kernel.event_listener, event: coreshop.shipment.post_transform, method: onOrderDocumentCreated }

    coreshop.workflow.order_id_wrapper_resolver:
        class: CoreShop\Bundle\OrderBundle\StateResolver\OrderIdPaymentStateResolver
        arguments:
            - '@coreshop.repository.order'
            - '@coreshop.state_machine_resolver.order_payment'