CoreShop\Component\Order\Model\CartPriceRuleVoucherCode:
  type: mappedSuperclass
  table: coreshop_cart_price_rule_voucher_code
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    code:
      column: code
      type: string
    creationDate:
      column: creationDate
      type: datetime
    used:
      column: used
      type: boolean
    uses:
      column: uses
      type: integer
  manyToOne:
    cartPriceRule:
      targetEntity: CoreShop\Component\Order\Model\CartPriceRuleInterface
      orphanRemoval: true
      inversedBy: voucherCodes
      joinColumn:
        name: cartPriceRuleId
