CoreShop\Component\Order\Model\CartPriceRuleTranslation:
    type: mappedSuperclass
    table: coreshop_cart_price_rule_translation
    fields:
        id:
            type: integer
            id: true
            generator:
              strategy: AUTO
        label:
            type: string
            nullable: true
        creationDate:
            type: date
            gedmo:
                timestampable:
                    on: create
        modificationDate:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
