coreshop_admin_cart_price_rule:
  type: coreshop.resources
  resource: |
    alias: coreshop.cart_price_rule
    additional_routes:
      config:
        path: get-config
        action: getConfig
        methods: [GET]
      getVoucherCodes:
        path: get-voucher-codes
        action: getVoucherCodes
        methods: [GET]
      getVoucherCodes:
        path: generate-voucher-codes
        action: generateVoucherCodes
        methods: [POST]
      exportVoucherCodes:
        path: export-voucher-codes
        action: exportVoucherCodes
        methods: [GET, POST]