framework:
    workflows:
        coreshop_order_invoice:
            type: 'state_machine'
            marking_store:
                service: coreshop.state_machine.marking_store.order_invoice_pimcore_marking_store
            supports: CoreShop\Component\Order\Model\Order
            places:
                - initialized
                - new
                - ready
                - cancelled
                - partially_invoiced
                - invoiced
            transitions:
                ready:
                    from: [initialized, new]
                    to: ready
                partially_invoiced:
                    from: [new, ready]
                    to: partially_invoiced
                cancel:
                    from: [new, ready]
                    to: cancelled
                invoiced:
                    from: [new, ready, partially_invoiced]
                    to: invoiced

core_shop_resource:
    state_machine:
        colors:
            coreshop_order_invoice:
                initialized: '#61c2cb'
                new: '#feb624'
                ready: '#feb624'
                partially_invoiced: '#f27024'
                invoiced: '#2c5600'
                canceled: '#f2583e'
        callbacks:
            coreshop_order_invoice:
                after:
                    resolve_state:
                        on: ['invoiced']
                        do: ['@coreshop.state_machine_resolver.order', 'resolve']
                        args: ['object']