core_shop_resource:
    state_machine:
        callbacks:
            coreshop_payment:
                after:
                  resolve_state:
                      on: ['complete', 'refund']
                      do: ['@coreshop.workflow.order_id_wrapper_resolver', 'resolveOrder']
                      args: ['object.getOrderId()']
                  restore_cart:
                      on: ['failed']
                      do: ['@coreshop.workflow.cart_recoverer', 'recover']
                      args: ['object.getOrderId()']
                  add_to_history:
                      on: ['process', 'complete', 'fail', 'cancel', 'refund']
                      do: ['@coreshop.workflow.state_history_logger', 'log']
                      args: ['object.getOrderId()', 'event']