framework:
    workflows:
        coreshop_shipment:
            type: 'state_machine'
            marking_store:
                service: coreshop.state_machine.marking_store.shipment_pimcore_marking_store
            supports: CoreShop\Component\Order\Model\OrderShipment
            places:
                - new
                - ready
                - cancelled
                - shipped
            transitions:
                create:
                    from: [new]
                    to: ready
                ship:
                    from: [ready]
                    to: shipped
                cancel:
                    from: [ready]
                    to: cancelled

core_shop_resource:
    state_machine:
        callbacks:
            coreshop_shipment:
                after:
                  resolve_state:
                      on: ['ship']
                      do: ['@coreshop.state_machine_resolver.order_shipment', 'resolve']
                      args: ['object.getOrder()']
                  add_to_history:
                      on: ['ship', 'cancel']
                      do: ['@coreshop.workflow.state_history_logger', 'log']
                      args: ['object.getOrder().getId()', 'event']