core_shop_resource:
    state_machine:
        callbacks:
            coreshop_payment:
                after:
                  resolve_state:
                      on: ['complete', 'refund']
                      do: ['@coreshop.state_machine_resolver.order_payment', 'resolve']
                      args: ["service('coreshop.repository.order').find(object.getOrderId())"]
                  add_to_history:
                      on: ['process', 'complete', 'fail', 'cancel', 'refund']
                      do: ['@coreshop.workflow.state_history_logger', 'log']
                      args: ['object.getOrderId()', 'event']