framework:
    workflows:
        coreshop_order_shipment:
            type: 'state_machine'
            marking_store:
                service: coreshop.state_machine.marking_store.order_shipment_pimcore_marking_store
            supports: CoreShop\Component\Order\Model\Order
            places:
                - new
                - cancelled
                - partially_shipped
                - shipped
            transitions:
                partially_ship:
                    from: [new]
                    to: partially_shipped
                cancel:
                    from: [new]
                    to: cancelled
                ship:
                    from: [new, partially_shipped]
                    to: shipped

core_shop_resource:
    state_machine:
        colors:
            coreshop_order_shipment:
                initialized: '#61c2cb'
                new: '#feb624'
                ready: '#feb624'
                partially_shipped: '#f27024'
                shipped: '#2c5600'
                cancelled: '#f2583e'
        callbacks:
            coreshop_order_shipment:
                after:
                    resolve_state:
                        on: ['ship']
                        do: ['@coreshop.state_machine_resolver.order', 'resolve']
                        args: ['object']