core_shop_resource:
    state_machine:
        callbacks:
            coreshop_payment:
                after:
                  # implement processors?
                  #process_order:
                    #on: ['fail', 'cancel']
                    #do: ['@coreshop.order_payment_processor', 'process']
                    #args: ['object.getOrder()']
                  resolve_state:
                      on: ['complete', 'refund']
                      do: ['@coreshop.state_machine_resolver.order_payment', 'resolve']
                      args: ['object.getOrder()']
                  add_to_history:
                      on: ['process', 'complete', 'fail', 'cancel', 'refund']
                      do: ['@coreshop.workflow.state_history_logger', 'log']
                      args: ['object.getOrderId()', 'event', ]