core_shop_resource:
    state_machine:
        callbacks:
            coreshop_payment:
                after:
                  # @todo: wrap getOrder() instead of getOrderId()?
                  resolve_state:
                      on: ['complete', 'refund']
                      do: ['@coreshop.state_machine_resolver.order_payment', 'resolve']
                      args: ['object.getOrderId()']
                  restore_cart:
                      on: ['cancel']
                      do: ['@coreshop.workflow.cart_recoverer', 'recover']
                      args: ['object.getOrderId()']
                  add_to_history:
                      on: ['process', 'complete', 'fail', 'cancel', 'refund']
                      do: ['@coreshop.workflow.state_history_logger', 'log']
                      args: ['object.getOrderId()', 'event']