framework:
    workflows:
        coreshop_order:
            type: 'state_machine'
            marking_store:
                service: coreshop.state_machine.marking_store.order_pimcore_marking_store
            supports: CoreShop\Component\Order\Model\Order
            places:
                - initialized
                - new
                - cancelled
                - complete
            transitions:
                create:
                    from: [initialized]
                    to: new
                cancel:
                    from: new
                    to:   cancelled
                complete:
                    from: new
                    to:   complete

core_shop_resource:
    state_machine:
        colors:
            coreshop_order:
                initialized: '#d6e1dd'
                new: '#61c2cb'
                cancelled: '#f2583e'
                complete: '#5b981a'
        callbacks:
            coreshop_order:
                after:
                    request_payment:
                        on: ['create']
                        do: ['@coreshop.state_machine_cascade_transition', 'apply']
                        args: ['object', 'event', '"request_payment"', '"coreshop_order_payment"']
                    cancel_payment:
                        on: ['cancel']
                        do: ['@coreshop.state_machine_cascade_transition', 'apply']
                        args: ['object.getPayments()', 'event', '"cancel"', '"coreshop_payment"']
                    cancel_shipment:
                        on: ['cancel']
                        do: ['@coreshop.state_machine_cascade_transition', 'apply']
                        args: ['object.getShipments()', 'event', '"cancel"', '"coreshop_shipment"']
                    cancel_invoice:
                        on: ['cancel']
                        do: ['@coreshop.state_machine_cascade_transition', 'apply']
                        args: ['object.getInvoices()', 'event', '"cancel"', '"coreshop_invoice"']
                    cancel_order_payment:
                        on: ['cancel']
                        do: ['@coreshop.state_machine_cascade_transition', 'apply']
                        args: ['object', 'event', '"cancel"', '"coreshop_order_payment"']
                    cancel_order_shipment:
                        on: ['cancel']
                        do: ['@coreshop.state_machine_cascade_transition', 'apply']
                        args: ['object', 'event', '"cancel"', '"coreshop_order_shipment"']
                    cancel_order_invoice:
                        on: ['cancel']
                        do: ['@coreshop.state_machine_cascade_transition', 'apply']
                        args: ['object', 'event', '"cancel"', '"coreshop_order_invoice"']
                    add_to_history:
                          on: ['create', 'cancel', 'complete']
                          do: ['@coreshop.workflow.state_history_logger', 'log']
                          args: ['object.getId()', 'event']