framework:
    workflows:
        coreshop_invoice:
            type: 'state_machine'
            marking_store:
                service: coreshop.state_machine.marking_store.invoice_pimcore_marking_store
            supports: CoreShop\Component\Order\Model\OrderInvoice
            places:
                - new
                - ready
                - cancelled
                - complete
            transitions:
                create:
                    from: [new]
                    to: ready
                cancel:
                    from: [ready]
                    to:   cancelled
                complete:
                    from: [ready]
                    to:   complete

core_shop_resource:
    state_machine:
        colors:
            coreshop_invoice:
                new: '#feb624'
                ready: '#feb624'
                cancelled: '#f2583e'
                complete: '#2c5600'
            coreshop_invoice_transition:
                create: '#feb624'
                cancel: '#f2583e'
                complete: '#2c5600'
        callbacks:
            coreshop_invoice:
                after:
                  resolve_state:
                      on: ['complete']
                      do: ['@coreshop.state_machine_resolver.order_invoice', 'resolve']
                      args: ['object.getOrder()']
                  add_to_history:
                      on: ['cancel', 'complete']
                      do: ['@coreshop.workflow.state_history_logger', 'log']
                      args: ['object.getOrder().getId()', 'event']