framework:
    workflows:
        coreshop_order_invoice:
            type: 'state_machine'
            marking_store:
                service: coreshop.state_machine.marking_store.order_invoice_pimcore_marking_store
            supports: CoreShop\Component\Order\Model\Order
            places:
                - new
                - cancelled
                - partially_invoiced
                - invoiced
            transitions:
                partially_invoice:
                    from: [new]
                    to: partially_invoiced
                cancel:
                    from: [new]
                    to: cancelled
                invoice:
                    from: [new, partially_invoiced]
                    to: invoiced

core_shop_resource:
    state_machine:
        colors:
            coreshop_order_invoice:
                initialized: '#61c2cb'
                new: '#feb624'
                ready: '#feb624'
                partially_invoiced: '#f27024'
                invoiced: '#5b981a'
                cancelled: '#f2583e'
        callbacks:
            coreshop_order_invoice:
                after:
                    resolve_state:
                        on: ['invoiced']
                        do: ['@coreshop.state_machine_resolver.order', 'resolve']
                        args: ['object']