CoreShop\Component\Order\Model\OrderShipment:
    exclusion_policy: ALL
    xml_root_name: order_shipment
    virtual_properties:
        id:
            serialized_name: id
            exp: object.getId()
            type: integer
            groups: [Detailed]
        documentType:
            serialized_name: documentType
            exp: object.getDocumentType()
            type: string
            groups: [Detailed]
        shipmentDate:
            serialized_name: shipmentDate
            exp: object.getShipmentDate()
            type: carbon
            groups: [Detailed]
        shipmentNumber:
            serialized_name: shipmentNumber
            exp: object.getShipmentNumber()
            type: string
            groups: [Detailed]
        trackingCode:
            serialized_name: trackingCode
            exp: object.getTrackingCode()
            type: string
            groups: [Detailed]
        items:
            serialized_name: items
            exp: object.getItems()
            type: array
            groups: [Detailed]
