CoreShop\Component\Order\Model\CartItem:
    exclusion_policy: ALL
    xml_root_name: cart_item
    virtual_properties:
        itemWholesalePrice:
            serialized_name: itemWholesalePrice
            exp: object.getItemWholesalePrice()
            type: integer
            groups: [Detailed]
        itemTax:
            serialized_name: itemTax
            exp: object.getItemTax()
            type: integer
            groups: [Detailed]
        product:
            serialized_name: product
            exp: object.getProduct()
            type: array
            groups: [Detailed]
        quantity:
            serialized_name: quantity
            exp: object.getQuantity()
            type: float
            groups: [Detailed]
        isGiftItem:
            serialized_name: isGiftItem
            exp: object.getIsGiftItem()
            type: boolean
            groups: [Detailed]
        taxes:
            serialized_name: taxes
            exp: object.getTaxes()
            type: array
            groups: [Detailed]
        adjustments:
            serialized_name: adjustments
            exp: object.getAdjustments()
            type: array
            groups: [Detailed]
        totalNet:
            serialized_name: totalNet
            exp: object.getTotal(false)
            type: integer
            groups: [Detailed]
        totalGross:
            serialized_name: totalGross
            exp: object.getTotal(true)
            type: integer
            groups: [Detailed]
        itemPriceNet:
            serialized_name: itemPriceNet
            exp: object.getItemPrice(false)
            type: integer
            groups: [Detailed]
        itemPriceGross:
            serialized_name: itemPriceGross
            exp: object.getItemPrice(true)
            type: integer
            groups: [Detailed]
        itemRetailPriceNet:
            serialized_name: itemRetailPriceNet
            exp: object.getItemRetailPrice(false)
            type: integer
            groups: [Detailed]
        itemRetailPriceGross:
            serialized_name: itemRetailPriceGross
            exp: object.getItemRetailPrice(true)
            type: integer
            groups: [Detailed]
        itemDiscountPriceNet:
            serialized_name: itemDiscountPriceNet
            exp: object.getItemDiscountPrice(false)
            type: integer
            groups: [Detailed]
        itemDiscountPriceGross:
            serialized_name: itemDiscountPriceGross
            exp: object.getItemDiscountPrice(true)
            type: integer
            groups: [Detailed]
        itemDiscountNet:
            serialized_name: itemDiscountNet
            exp: object.getItemDiscount(false)
            type: integer
            groups: [Detailed]
        itemDiscountGross:
            serialized_name: itemDiscountGross
            exp: object.getItemDiscount(true)
            type: integer
            groups: [Detailed]
        totalTax:
            serialized_name: totalTax
            exp: object.getTotalTax()
            type: integer
            groups: [Detailed]
