CoreShop\Component\Order\Model\SaleItem:
    exclusion_policy: ALL
    xml_root_name: sale_item
    virtual_properties:
        name:
            serialized_name: name
            exp: object.getName()
            type: string
            groups: [Detailed]
        isGiftItem:
            serialized_name: isGiftItem
            exp: object.getIsGiftItem()
            type: boolean
            groups: [Detailed]
        itemTax:
            serialized_name: itemTax
            exp: object.getItemTax()
            type: integer
            groups: [Detailed]
        baseItemTax:
            serialized_name: baseItemTax
            exp: object.getBaseItemTax()
            type: integer
            groups: [Detailed]
        itemWholesalePrice:
            serialized_name: itemWholesalePrice
            exp: object.getItemWholesalePrice()
            type: integer
            groups: [Detailed]
        baseItemWholesalePrice:
            serialized_name: baseItemWholesalePrice
            exp: object.getBaseItemWholesalePrice()
            type: integer
            groups: [Detailed]
        taxes:
            serialized_name: taxes
            exp: object.getTaxes()
            type: array
            groups: [Detailed]
        baseTaxes:
            serialized_name: baseTaxes
            exp: object.getBaseTaxes()
            type: array
            groups: [Detailed]
        product:
            serialized_name: product
            exp: object.getProduct()
            groups: [Detailed]
        quantity:
            serialized_name: quantity
            exp: object.getQuantity()
            type: float
            groups: [Detailed]
        totalTax:
            serialized_name: totalTax
            exp: object.getTotalTax()
            type: integer
            groups: [Detailed]
        baseTotalTax:
            serialized_name: baseTotalTax
            exp: object.getBaseTotalTax(true)
            type: integer
            groups: [Detailed]
        itemPriceNet:
            serialized_name: itemPriceNet
            exp: object.getItemPrice(false)
            type: integer
            groups: [Detailed]
        itemPriceGross:
            serialized_name: itemPriceGross
            exp: object.getItemPrice(true)
            type: integer
            groups: [Detailed]
        baseItemPriceNet:
            serialized_name: baseItemPriceNet
            exp: object.getBaseItemPrice(false)
            type: integer
            groups: [Detailed]
        baseItemPriceGross:
            serialized_name: baseItemPriceGross
            exp: object.getBaseItemPrice(true)
            type: integer
            groups: [Detailed]
        itemRetailPriceNet:
            serialized_name: itemRetailPriceNet
            exp: object.getItemRetailPrice(false)
            type: integer
            groups: [Detailed]
        itemRetailPriceGross:
            serialized_name: itemRetailPriceGross
            exp: object.getItemRetailPrice(true)
            type: integer
            groups: [Detailed]
        baseItemRetailPriceNet:
            serialized_name: baseItemRetailPriceNet
            exp: object.getBaseItemRetailPrice(false)
            type: integer
            groups: [Detailed]
        baseItemRetailPriceGross:
            serialized_name: baseItemRetailPriceGross
            exp: object.getBaseItemRetailPrice(true)
            type: integer
            groups: [Detailed]
        itemDiscountPriceNet:
            serialized_name: itemDiscountPriceNet
            exp: object.getItemDiscountPrice(false)
            type: integer
            groups: [Detailed]
        itemDiscountPriceGross:
            serialized_name: itemDiscountPriceGross
            exp: object.getItemDiscountPrice(true)
            type: integer
            groups: [Detailed]
        itemDiscountNet:
            serialized_name: itemDiscountNet
            exp: object.getItemDiscount(false)
            type: integer
            groups: [Detailed]
        itemDiscountGross:
            serialized_name: itemDiscountGross
            exp: object.getItemDiscount(true)
            type: integer
            groups: [Detailed]
        totalNet:
            serialized_name: totalNet
            exp: object.getTotal(false)
            type: integer
            groups: [Detailed]
        totalGross:
            serialized_name: totalGross
            exp: object.getTotal(true)
            type: integer
            groups: [Detailed]
        baseTotalNet:
            serialized_name: baseTotalNet
            exp: object.getBaseTotal(false)
            type: integer
            groups: [Detailed]
        baseTotalGross:
            serialized_name: baseTotalGross
            exp: object.getBaseTotal(true)
            type: integer
            groups: [Detailed]
        adjustments:
            serialized_name: adjustments
            exp: object.getAdjustments()
            type: array
            groups: [Detailed]
        baseAdjustments:
            serialized_name: baseAdjustments
            exp: object.getBaseAdjustments()
            type: array
            groups: [Detailed]
