CoreShop\Component\Order\Model\CartItem:
    getters:
        quantity:
            - NotBlank: { message: coreshop.cart_item.quantity.not_blank, groups: coreshop }
            - Type: { type: integer, message: coreshop.cart_item.quantity.integer, groups: coreshop }
            - Range: { min: 1, minMessage: coreshop.cart_item.quantity.min, groups: coreshop }